### ISSUE TITLE
Consider supporting font selection

### ISSUE THREAD

**Issue by lread** [phronmophobic/membrane.term#2]
**Proposal**
Same vein as #1 but for specifying fonts.

It would be nice to be able to specify font size.
It would be super nice to be able to specify the font itself.

This might be super easy, or maybe have nuances I'm not aware of.

**Next steps** 
If you are interested in this idea, same offer as #1, happy to take a crack at it!
But also don't want to get in your way if this work entices you.

**Comment by lread** [comment]
Ok, now thinking about this one!

Initial ramblings...

How about `--font-face` and `--font-size` for options (`:font-face` and `:font-size` internally).
If I understand correctly, font size unit is points?

What about specifying something like a [google font](https://fonts.google.com/?category=Monospace) directly from the web? 
Maybe too complicated for user to specify?
Not sure how that would work, just throwing the idea out there. I do see some support in skija for typefaces... but yeah, unless you know something that would make this simple, seems a bit much for a first cut.

But we could certainly document google fonts and [nerd fonts](https://www.nerdfonts.com/) as interesting places to find monospace fonts.

I think I'll separate out support rendering of vt underline,blink,inverse and strikethrough to its own issue.

**Comment by phronmophobic** [comment]
I'm trying to use the same terminology that Skia uses for fonts which I think is:
Font: TypeFace + size
TypeFace: FamilyName + FontStyle
FontStyle: Width + Weight + Slant
Width: normal, condensed, expanded (less commonly specified)
Weight: normal, bold, extra bold, thin, etc.
Slant: Upright (aka. normal), Italic

Based on that, I would suggest either `:font-name` or `:font-family` or `:font-family-name`. 

`:font-size` is 👍 

> If I understand correctly, font size unit is points?

I think so.

> What about specifying something like a google font directly from the web?

You can pass a path to a font file like ttf or ttc as the name for `membrane.ui/font`. There's some tricky business since formats like ttc can contain multiple typefaces. Text rendering is a whole thing that I'm still trying to learn and improve my understanding on. Since I'm using skia for text rendering, the io/reader trick won't quite work. However, google fonts does let you download font files.

Hopefully, skia uses the text related terminology correctly! If not, it would be good to have another reference to follow. Otherwise, it becomes tricky to talk about all the weird issues with text+fonts.

References.
https://api.skia.org/classSkFont.html
https://api.skia.org/classSkTypeface.html#a1cd98b2bdf57d80e06917c24c5526b59
https://api.skia.org/classSkFontStyle.html

**Comment by lread** [comment]
Thanks, the glossary helps!

HTML/CSS uses `font-family`, so that seems like a good choice.
Since the screen size is computed from font character dimensions, we won't have any conversions to think about. (So the font size unit is not that important after all, I think).

Anything we want to do if the user selects a proportional (non-monospace) font?

I think that only supporting OS-installed fonts for a first cut is reasonable.
How about you?

**Comment by phronmophobic** [comment]
> Anything we want to do if the user selects a proportional (non-monospace) font?

I just checked to see what my macbook's built in terminal does. It looks like they just use the max character advance for every character? I'm basically ok with anything that doesn't crash as trying to use a non-monospace font doesn't really make sense.

> I think that only supporting OS-installed fonts for a first cut is reasonable.
> How about you?

👍

**Comment by lread** [comment]
@phronmophobic, have you tried fancy prompts like [powerlevel10k](https://github.com/romkatv/powerlevel10k) under zsh with membrane.term? 

I wonder if I have a font-related, or some other (or both) issue.

Here's a zsh powerlevel10k session in iTerm2 using the recommended "MesloLGS NF" font.
![image](https://user-images.githubusercontent.com/967328/139776133-f305aade-99fe-471a-9b4d-3daf65807392.png)

And here's the same using membrane.term (looking pretty nice, BTW!):
![image](https://user-images.githubusercontent.com/967328/139776162-1915c469-6d80-4a90-8278-1e04091a1d77.png)

But...
- Not sure yet why I'm not seeing the little happy glyphs. Maybe unicode not enabled somewhere? Ah.. that's probably it. 
  - From iTerm2:
    ```
    ❯ echo -e '\U0001f602'
    😂
    ```
  - From membrane.term don't see the little emoji.
- And the time is not justified right.
- And tangental but... the cursor seems off by one maybe?

Might be a asciinema/vt thing. Will look deeper but thought I'd ping you to see if you were already aware.

**Comment by phronmophobic** [comment]
Just looking at https://github.com/romkatv/powerlevel10k/blob/master/font.md#manual-font-installation, it doesn't look like that font actually contains the emoji characters. I know that usually there are different fonts that apply for different character ranges, but I'm actually not totally sure how that works.

**Comment by phronmophobic** [comment]
Even if we wanted to use multiple fonts depending on the character range, I'm not sure how to ask for the default emoji font on the system. I'll try to look it up.

**Comment by phronmophobic** [comment]
You can display emoji by using the font family: "Apple Color Emoji". Trying to see if there's a way to pull up the default system emoji font like "monospaced" does for mono space fonts.

**Comment by lread** [comment]
Thanks! [He's added a bunch of glyphs](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k). But I can't say I understand much of this yet.
The NF stands for Nerd Font which [implies the glyphs](https://www.nerdfonts.com/).

Here's maybe a better example from iTerm2 using the "MesloLGS NF" font:
![image](https://user-images.githubusercontent.com/967328/139781163-f6355b35-038f-4c60-9412-f6eb999a1a11.png)

If I switch to a non-Nerd Font like Menlo I lose the glyphs:
![image](https://user-images.githubusercontent.com/967328/139781386-fc242e37-d9f9-4b26-a17c-3f05b8d24d28.png)

I switch to another Nerd Font like "Hack Nerd Font" the glyphs are back:
![image](https://user-images.githubusercontent.com/967328/139781601-d1df23cd-cd58-4ee5-a04e-eeaea2ee55b7.png)

**Comment by lread** [comment]
Oho, a bit askew but:
![image](https://user-images.githubusercontent.com/967328/139923090-9457542b-fbde-47a0-942b-fa4de7e0d22f.png)

We were reading bytes from the pty input stream, switching to reading chars got us the unicode.

Fully supporting Unicode in terminals might be a bit complex though?
I'll try to figure out what minimal support means.

We probably don't need to be as thorough as, for example, the [Countour terminal](https://github.com/contour-terminal/contour) folks [are being](https://github.com/contour-terminal/terminal-unicode-core).

**Comment by phronmophobic** [comment]
> We were reading bytes from the pty input stream, switching to reading chars got us the Unicode.

Wow! Not bad. Good catch!

> Fully supporting Unicode in terminals might be a bit complex though?
> I'll try to figure out what minimal support means.

I imagine that full unicode support would probably require changes to membrane. There's a lot of text improvements I'd like to make, but there are a few other priorities at the moment.
